spring:
  application:
    name: api-service

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: cap-service
          uri: lb://cap-service
          predicates:
            - Path=/cap/**
          filters:
            - RewritePath=/cap/(?<path>.*), /$\{path}

        - id: daa-service
          uri: lb://daa-service
          predicates:
            - Path=/daa/**
          filters:
            - RewritePath=/daa/(?<path>.*), /$\{path}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8080

springdoc:
  swagger-ui:
    urls:
      - name: cars and parts
        url: cap/v3/api-docs
      - name: drivers and accounts
        url: daa/v3/api-docs
